//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SoftInvBusiness.almacenesWS {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://services.softinv.pucp.edu.pe/", ConfigurationName="almacenesWS.Almacenes")]
    public interface Almacenes {
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.softinv.pucp.edu.pe/Almacenes/obtenerPorIdRequest", ReplyAction="http://services.softinv.pucp.edu.pe/Almacenes/obtenerPorIdResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        SoftInvBusiness.almacenesWS.obtenerPorIdResponse obtenerPorId(SoftInvBusiness.almacenesWS.obtenerPorIdRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.softinv.pucp.edu.pe/Almacenes/obtenerPorIdRequest", ReplyAction="http://services.softinv.pucp.edu.pe/Almacenes/obtenerPorIdResponse")]
        System.Threading.Tasks.Task<SoftInvBusiness.almacenesWS.obtenerPorIdResponse> obtenerPorIdAsync(SoftInvBusiness.almacenesWS.obtenerPorIdRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.softinv.pucp.edu.pe/Almacenes/listarTodosRequest", ReplyAction="http://services.softinv.pucp.edu.pe/Almacenes/listarTodosResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        SoftInvBusiness.almacenesWS.listarTodosResponse listarTodos(SoftInvBusiness.almacenesWS.listarTodosRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.softinv.pucp.edu.pe/Almacenes/listarTodosRequest", ReplyAction="http://services.softinv.pucp.edu.pe/Almacenes/listarTodosResponse")]
        System.Threading.Tasks.Task<SoftInvBusiness.almacenesWS.listarTodosResponse> listarTodosAsync(SoftInvBusiness.almacenesWS.listarTodosRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.softinv.pucp.edu.pe/Almacenes/eliminarRequest", ReplyAction="http://services.softinv.pucp.edu.pe/Almacenes/eliminarResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        SoftInvBusiness.almacenesWS.eliminarResponse eliminar(SoftInvBusiness.almacenesWS.eliminarRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.softinv.pucp.edu.pe/Almacenes/eliminarRequest", ReplyAction="http://services.softinv.pucp.edu.pe/Almacenes/eliminarResponse")]
        System.Threading.Tasks.Task<SoftInvBusiness.almacenesWS.eliminarResponse> eliminarAsync(SoftInvBusiness.almacenesWS.eliminarRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.softinv.pucp.edu.pe/Almacenes/modificarRequest", ReplyAction="http://services.softinv.pucp.edu.pe/Almacenes/modificarResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        SoftInvBusiness.almacenesWS.modificarResponse modificar(SoftInvBusiness.almacenesWS.modificarRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.softinv.pucp.edu.pe/Almacenes/modificarRequest", ReplyAction="http://services.softinv.pucp.edu.pe/Almacenes/modificarResponse")]
        System.Threading.Tasks.Task<SoftInvBusiness.almacenesWS.modificarResponse> modificarAsync(SoftInvBusiness.almacenesWS.modificarRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.softinv.pucp.edu.pe/Almacenes/insertarRequest", ReplyAction="http://services.softinv.pucp.edu.pe/Almacenes/insertarResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        SoftInvBusiness.almacenesWS.insertarResponse insertar(SoftInvBusiness.almacenesWS.insertarRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.softinv.pucp.edu.pe/Almacenes/insertarRequest", ReplyAction="http://services.softinv.pucp.edu.pe/Almacenes/insertarResponse")]
        System.Threading.Tasks.Task<SoftInvBusiness.almacenesWS.insertarResponse> insertarAsync(SoftInvBusiness.almacenesWS.insertarRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.softinv.pucp.edu.pe/")]
    public partial class almacenesDTO : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int almacenIdField;
        
        private bool almacenIdFieldSpecified;
        
        private bool almacen_centralField;
        
        private bool almacen_centralFieldSpecified;
        
        private string nombreField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int almacenId {
            get {
                return this.almacenIdField;
            }
            set {
                this.almacenIdField = value;
                this.RaisePropertyChanged("almacenId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool almacenIdSpecified {
            get {
                return this.almacenIdFieldSpecified;
            }
            set {
                this.almacenIdFieldSpecified = value;
                this.RaisePropertyChanged("almacenIdSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public bool almacen_central {
            get {
                return this.almacen_centralField;
            }
            set {
                this.almacen_centralField = value;
                this.RaisePropertyChanged("almacen_central");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool almacen_centralSpecified {
            get {
                return this.almacen_centralFieldSpecified;
            }
            set {
                this.almacen_centralFieldSpecified = value;
                this.RaisePropertyChanged("almacen_centralSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
                this.RaisePropertyChanged("nombre");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="obtenerPorId", WrapperNamespace="http://services.softinv.pucp.edu.pe/", IsWrapped=true)]
    public partial class obtenerPorIdRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.softinv.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int almacenId;
        
        public obtenerPorIdRequest() {
        }
        
        public obtenerPorIdRequest(int almacenId) {
            this.almacenId = almacenId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="obtenerPorIdResponse", WrapperNamespace="http://services.softinv.pucp.edu.pe/", IsWrapped=true)]
    public partial class obtenerPorIdResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.softinv.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SoftInvBusiness.almacenesWS.almacenesDTO @return;
        
        public obtenerPorIdResponse() {
        }
        
        public obtenerPorIdResponse(SoftInvBusiness.almacenesWS.almacenesDTO @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarTodos", WrapperNamespace="http://services.softinv.pucp.edu.pe/", IsWrapped=true)]
    public partial class listarTodosRequest {
        
        public listarTodosRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarTodosResponse", WrapperNamespace="http://services.softinv.pucp.edu.pe/", IsWrapped=true)]
    public partial class listarTodosResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.softinv.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SoftInvBusiness.almacenesWS.almacenesDTO[] @return;
        
        public listarTodosResponse() {
        }
        
        public listarTodosResponse(SoftInvBusiness.almacenesWS.almacenesDTO[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="eliminar", WrapperNamespace="http://services.softinv.pucp.edu.pe/", IsWrapped=true)]
    public partial class eliminarRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.softinv.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int almacenId;
        
        public eliminarRequest() {
        }
        
        public eliminarRequest(int almacenId) {
            this.almacenId = almacenId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="eliminarResponse", WrapperNamespace="http://services.softinv.pucp.edu.pe/", IsWrapped=true)]
    public partial class eliminarResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.softinv.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public eliminarResponse() {
        }
        
        public eliminarResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="modificar", WrapperNamespace="http://services.softinv.pucp.edu.pe/", IsWrapped=true)]
    public partial class modificarRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.softinv.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int almacenId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.softinv.pucp.edu.pe/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string nombre;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.softinv.pucp.edu.pe/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool almacen_central;
        
        public modificarRequest() {
        }
        
        public modificarRequest(int almacenId, string nombre, bool almacen_central) {
            this.almacenId = almacenId;
            this.nombre = nombre;
            this.almacen_central = almacen_central;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="modificarResponse", WrapperNamespace="http://services.softinv.pucp.edu.pe/", IsWrapped=true)]
    public partial class modificarResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.softinv.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public modificarResponse() {
        }
        
        public modificarResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="insertar", WrapperNamespace="http://services.softinv.pucp.edu.pe/", IsWrapped=true)]
    public partial class insertarRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.softinv.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string nombre;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.softinv.pucp.edu.pe/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool almacen_central;
        
        public insertarRequest() {
        }
        
        public insertarRequest(string nombre, bool almacen_central) {
            this.nombre = nombre;
            this.almacen_central = almacen_central;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="insertarResponse", WrapperNamespace="http://services.softinv.pucp.edu.pe/", IsWrapped=true)]
    public partial class insertarResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.softinv.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public insertarResponse() {
        }
        
        public insertarResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface AlmacenesChannel : SoftInvBusiness.almacenesWS.Almacenes, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AlmacenesClient : System.ServiceModel.ClientBase<SoftInvBusiness.almacenesWS.Almacenes>, SoftInvBusiness.almacenesWS.Almacenes {
        
        public AlmacenesClient() {
        }
        
        public AlmacenesClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AlmacenesClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AlmacenesClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AlmacenesClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SoftInvBusiness.almacenesWS.obtenerPorIdResponse SoftInvBusiness.almacenesWS.Almacenes.obtenerPorId(SoftInvBusiness.almacenesWS.obtenerPorIdRequest request) {
            return base.Channel.obtenerPorId(request);
        }
        
        public SoftInvBusiness.almacenesWS.almacenesDTO obtenerPorId(int almacenId) {
            SoftInvBusiness.almacenesWS.obtenerPorIdRequest inValue = new SoftInvBusiness.almacenesWS.obtenerPorIdRequest();
            inValue.almacenId = almacenId;
            SoftInvBusiness.almacenesWS.obtenerPorIdResponse retVal = ((SoftInvBusiness.almacenesWS.Almacenes)(this)).obtenerPorId(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SoftInvBusiness.almacenesWS.obtenerPorIdResponse> SoftInvBusiness.almacenesWS.Almacenes.obtenerPorIdAsync(SoftInvBusiness.almacenesWS.obtenerPorIdRequest request) {
            return base.Channel.obtenerPorIdAsync(request);
        }
        
        public System.Threading.Tasks.Task<SoftInvBusiness.almacenesWS.obtenerPorIdResponse> obtenerPorIdAsync(int almacenId) {
            SoftInvBusiness.almacenesWS.obtenerPorIdRequest inValue = new SoftInvBusiness.almacenesWS.obtenerPorIdRequest();
            inValue.almacenId = almacenId;
            return ((SoftInvBusiness.almacenesWS.Almacenes)(this)).obtenerPorIdAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SoftInvBusiness.almacenesWS.listarTodosResponse SoftInvBusiness.almacenesWS.Almacenes.listarTodos(SoftInvBusiness.almacenesWS.listarTodosRequest request) {
            return base.Channel.listarTodos(request);
        }
        
        public SoftInvBusiness.almacenesWS.almacenesDTO[] listarTodos() {
            SoftInvBusiness.almacenesWS.listarTodosRequest inValue = new SoftInvBusiness.almacenesWS.listarTodosRequest();
            SoftInvBusiness.almacenesWS.listarTodosResponse retVal = ((SoftInvBusiness.almacenesWS.Almacenes)(this)).listarTodos(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SoftInvBusiness.almacenesWS.listarTodosResponse> SoftInvBusiness.almacenesWS.Almacenes.listarTodosAsync(SoftInvBusiness.almacenesWS.listarTodosRequest request) {
            return base.Channel.listarTodosAsync(request);
        }
        
        public System.Threading.Tasks.Task<SoftInvBusiness.almacenesWS.listarTodosResponse> listarTodosAsync() {
            SoftInvBusiness.almacenesWS.listarTodosRequest inValue = new SoftInvBusiness.almacenesWS.listarTodosRequest();
            return ((SoftInvBusiness.almacenesWS.Almacenes)(this)).listarTodosAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SoftInvBusiness.almacenesWS.eliminarResponse SoftInvBusiness.almacenesWS.Almacenes.eliminar(SoftInvBusiness.almacenesWS.eliminarRequest request) {
            return base.Channel.eliminar(request);
        }
        
        public int eliminar(int almacenId) {
            SoftInvBusiness.almacenesWS.eliminarRequest inValue = new SoftInvBusiness.almacenesWS.eliminarRequest();
            inValue.almacenId = almacenId;
            SoftInvBusiness.almacenesWS.eliminarResponse retVal = ((SoftInvBusiness.almacenesWS.Almacenes)(this)).eliminar(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SoftInvBusiness.almacenesWS.eliminarResponse> SoftInvBusiness.almacenesWS.Almacenes.eliminarAsync(SoftInvBusiness.almacenesWS.eliminarRequest request) {
            return base.Channel.eliminarAsync(request);
        }
        
        public System.Threading.Tasks.Task<SoftInvBusiness.almacenesWS.eliminarResponse> eliminarAsync(int almacenId) {
            SoftInvBusiness.almacenesWS.eliminarRequest inValue = new SoftInvBusiness.almacenesWS.eliminarRequest();
            inValue.almacenId = almacenId;
            return ((SoftInvBusiness.almacenesWS.Almacenes)(this)).eliminarAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SoftInvBusiness.almacenesWS.modificarResponse SoftInvBusiness.almacenesWS.Almacenes.modificar(SoftInvBusiness.almacenesWS.modificarRequest request) {
            return base.Channel.modificar(request);
        }
        
        public int modificar(int almacenId, string nombre, bool almacen_central) {
            SoftInvBusiness.almacenesWS.modificarRequest inValue = new SoftInvBusiness.almacenesWS.modificarRequest();
            inValue.almacenId = almacenId;
            inValue.nombre = nombre;
            inValue.almacen_central = almacen_central;
            SoftInvBusiness.almacenesWS.modificarResponse retVal = ((SoftInvBusiness.almacenesWS.Almacenes)(this)).modificar(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SoftInvBusiness.almacenesWS.modificarResponse> SoftInvBusiness.almacenesWS.Almacenes.modificarAsync(SoftInvBusiness.almacenesWS.modificarRequest request) {
            return base.Channel.modificarAsync(request);
        }
        
        public System.Threading.Tasks.Task<SoftInvBusiness.almacenesWS.modificarResponse> modificarAsync(int almacenId, string nombre, bool almacen_central) {
            SoftInvBusiness.almacenesWS.modificarRequest inValue = new SoftInvBusiness.almacenesWS.modificarRequest();
            inValue.almacenId = almacenId;
            inValue.nombre = nombre;
            inValue.almacen_central = almacen_central;
            return ((SoftInvBusiness.almacenesWS.Almacenes)(this)).modificarAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SoftInvBusiness.almacenesWS.insertarResponse SoftInvBusiness.almacenesWS.Almacenes.insertar(SoftInvBusiness.almacenesWS.insertarRequest request) {
            return base.Channel.insertar(request);
        }
        
        public int insertar(string nombre, bool almacen_central) {
            SoftInvBusiness.almacenesWS.insertarRequest inValue = new SoftInvBusiness.almacenesWS.insertarRequest();
            inValue.nombre = nombre;
            inValue.almacen_central = almacen_central;
            SoftInvBusiness.almacenesWS.insertarResponse retVal = ((SoftInvBusiness.almacenesWS.Almacenes)(this)).insertar(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SoftInvBusiness.almacenesWS.insertarResponse> SoftInvBusiness.almacenesWS.Almacenes.insertarAsync(SoftInvBusiness.almacenesWS.insertarRequest request) {
            return base.Channel.insertarAsync(request);
        }
        
        public System.Threading.Tasks.Task<SoftInvBusiness.almacenesWS.insertarResponse> insertarAsync(string nombre, bool almacen_central) {
            SoftInvBusiness.almacenesWS.insertarRequest inValue = new SoftInvBusiness.almacenesWS.insertarRequest();
            inValue.nombre = nombre;
            inValue.almacen_central = almacen_central;
            return ((SoftInvBusiness.almacenesWS.Almacenes)(this)).insertarAsync(inValue);
        }
    }
}
