//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SoftInvBusiness.clienteSOAP {
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.softinv.pucp.edu.pe/")]
    public partial class IOException : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string messageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
                this.RaisePropertyChanged("message");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.softinv.pucp.edu.pe/")]
    public partial class almacenesDTO : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int almacenIdField;
        
        private bool almacenIdFieldSpecified;
        
        private bool almacen_centralField;
        
        private bool almacen_centralFieldSpecified;
        
        private string nombreField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int almacenId {
            get {
                return this.almacenIdField;
            }
            set {
                this.almacenIdField = value;
                this.RaisePropertyChanged("almacenId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool almacenIdSpecified {
            get {
                return this.almacenIdFieldSpecified;
            }
            set {
                this.almacenIdFieldSpecified = value;
                this.RaisePropertyChanged("almacenIdSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public bool almacen_central {
            get {
                return this.almacen_centralField;
            }
            set {
                this.almacen_centralField = value;
                this.RaisePropertyChanged("almacen_central");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool almacen_centralSpecified {
            get {
                return this.almacen_centralFieldSpecified;
            }
            set {
                this.almacen_centralFieldSpecified = value;
                this.RaisePropertyChanged("almacen_centralSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
                this.RaisePropertyChanged("nombre");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.softinv.pucp.edu.pe/")]
    public partial class InterruptedException : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string messageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
                this.RaisePropertyChanged("message");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.softinv.pucp.edu.pe/")]
    public partial class JsonProcessingException : object, System.ComponentModel.INotifyPropertyChanged {
        
        private jsonLocation locationField;
        
        private string messageField;
        
        private string originalMessageField;
        
        private object processorField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public jsonLocation location {
            get {
                return this.locationField;
            }
            set {
                this.locationField = value;
                this.RaisePropertyChanged("location");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
                this.RaisePropertyChanged("message");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string originalMessage {
            get {
                return this.originalMessageField;
            }
            set {
                this.originalMessageField = value;
                this.RaisePropertyChanged("originalMessage");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public object processor {
            get {
                return this.processorField;
            }
            set {
                this.processorField = value;
                this.RaisePropertyChanged("processor");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.softinv.pucp.edu.pe/")]
    public partial class jsonLocation : object, System.ComponentModel.INotifyPropertyChanged {
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://services.softinv.pucp.edu.pe/", ConfigurationName="clienteSOAP.Almacenes")]
    public interface Almacenes {
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.softinv.pucp.edu.pe/Almacenes/obtenerPorIdRequest", ReplyAction="http://services.softinv.pucp.edu.pe/Almacenes/obtenerPorIdResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(SoftInvBusiness.clienteSOAP.IOException), Action="http://services.softinv.pucp.edu.pe/Almacenes/obtenerPorId/Fault/IOException", Name="IOException")]
        [System.ServiceModel.FaultContractAttribute(typeof(SoftInvBusiness.clienteSOAP.InterruptedException), Action="http://services.softinv.pucp.edu.pe/Almacenes/obtenerPorId/Fault/InterruptedExcep" +
            "tion", Name="InterruptedException")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        SoftInvBusiness.clienteSOAP.obtenerPorIdResponse obtenerPorId(SoftInvBusiness.clienteSOAP.obtenerPorIdRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.softinv.pucp.edu.pe/Almacenes/obtenerPorIdRequest", ReplyAction="http://services.softinv.pucp.edu.pe/Almacenes/obtenerPorIdResponse")]
        System.Threading.Tasks.Task<SoftInvBusiness.clienteSOAP.obtenerPorIdResponse> obtenerPorIdAsync(SoftInvBusiness.clienteSOAP.obtenerPorIdRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.softinv.pucp.edu.pe/Almacenes/inserta_almacenRequest", ReplyAction="http://services.softinv.pucp.edu.pe/Almacenes/inserta_almacenResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(SoftInvBusiness.clienteSOAP.IOException), Action="http://services.softinv.pucp.edu.pe/Almacenes/inserta_almacen/Fault/IOException", Name="IOException")]
        [System.ServiceModel.FaultContractAttribute(typeof(SoftInvBusiness.clienteSOAP.JsonProcessingException), Action="http://services.softinv.pucp.edu.pe/Almacenes/inserta_almacen/Fault/JsonProcessin" +
            "gException", Name="JsonProcessingException")]
        [System.ServiceModel.FaultContractAttribute(typeof(SoftInvBusiness.clienteSOAP.InterruptedException), Action="http://services.softinv.pucp.edu.pe/Almacenes/inserta_almacen/Fault/InterruptedEx" +
            "ception", Name="InterruptedException")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        SoftInvBusiness.clienteSOAP.inserta_almacenResponse inserta_almacen(SoftInvBusiness.clienteSOAP.inserta_almacenRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.softinv.pucp.edu.pe/Almacenes/inserta_almacenRequest", ReplyAction="http://services.softinv.pucp.edu.pe/Almacenes/inserta_almacenResponse")]
        System.Threading.Tasks.Task<SoftInvBusiness.clienteSOAP.inserta_almacenResponse> inserta_almacenAsync(SoftInvBusiness.clienteSOAP.inserta_almacenRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.softinv.pucp.edu.pe/Almacenes/eliminarRequest", ReplyAction="http://services.softinv.pucp.edu.pe/Almacenes/eliminarResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(SoftInvBusiness.clienteSOAP.IOException), Action="http://services.softinv.pucp.edu.pe/Almacenes/eliminar/Fault/IOException", Name="IOException")]
        [System.ServiceModel.FaultContractAttribute(typeof(SoftInvBusiness.clienteSOAP.InterruptedException), Action="http://services.softinv.pucp.edu.pe/Almacenes/eliminar/Fault/InterruptedException" +
            "", Name="InterruptedException")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        SoftInvBusiness.clienteSOAP.eliminarResponse eliminar(SoftInvBusiness.clienteSOAP.eliminarRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.softinv.pucp.edu.pe/Almacenes/eliminarRequest", ReplyAction="http://services.softinv.pucp.edu.pe/Almacenes/eliminarResponse")]
        System.Threading.Tasks.Task<SoftInvBusiness.clienteSOAP.eliminarResponse> eliminarAsync(SoftInvBusiness.clienteSOAP.eliminarRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.softinv.pucp.edu.pe/Almacenes/modificarRequest", ReplyAction="http://services.softinv.pucp.edu.pe/Almacenes/modificarResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(SoftInvBusiness.clienteSOAP.IOException), Action="http://services.softinv.pucp.edu.pe/Almacenes/modificar/Fault/IOException", Name="IOException")]
        [System.ServiceModel.FaultContractAttribute(typeof(SoftInvBusiness.clienteSOAP.JsonProcessingException), Action="http://services.softinv.pucp.edu.pe/Almacenes/modificar/Fault/JsonProcessingExcep" +
            "tion", Name="JsonProcessingException")]
        [System.ServiceModel.FaultContractAttribute(typeof(SoftInvBusiness.clienteSOAP.InterruptedException), Action="http://services.softinv.pucp.edu.pe/Almacenes/modificar/Fault/InterruptedExceptio" +
            "n", Name="InterruptedException")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        SoftInvBusiness.clienteSOAP.modificarResponse modificar(SoftInvBusiness.clienteSOAP.modificarRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.softinv.pucp.edu.pe/Almacenes/modificarRequest", ReplyAction="http://services.softinv.pucp.edu.pe/Almacenes/modificarResponse")]
        System.Threading.Tasks.Task<SoftInvBusiness.clienteSOAP.modificarResponse> modificarAsync(SoftInvBusiness.clienteSOAP.modificarRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.softinv.pucp.edu.pe/Almacenes/reporteTipoProductoRequest", ReplyAction="http://services.softinv.pucp.edu.pe/Almacenes/reporteTipoProductoResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        SoftInvBusiness.clienteSOAP.reporteTipoProductoResponse reporteTipoProducto(SoftInvBusiness.clienteSOAP.reporteTipoProductoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.softinv.pucp.edu.pe/Almacenes/reporteTipoProductoRequest", ReplyAction="http://services.softinv.pucp.edu.pe/Almacenes/reporteTipoProductoResponse")]
        System.Threading.Tasks.Task<SoftInvBusiness.clienteSOAP.reporteTipoProductoResponse> reporteTipoProductoAsync(SoftInvBusiness.clienteSOAP.reporteTipoProductoRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.softinv.pucp.edu.pe/Almacenes/reporteProductoRequest", ReplyAction="http://services.softinv.pucp.edu.pe/Almacenes/reporteProductoResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        SoftInvBusiness.clienteSOAP.reporteProductoResponse reporteProducto(SoftInvBusiness.clienteSOAP.reporteProductoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.softinv.pucp.edu.pe/Almacenes/reporteProductoRequest", ReplyAction="http://services.softinv.pucp.edu.pe/Almacenes/reporteProductoResponse")]
        System.Threading.Tasks.Task<SoftInvBusiness.clienteSOAP.reporteProductoResponse> reporteProductoAsync(SoftInvBusiness.clienteSOAP.reporteProductoRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.softinv.pucp.edu.pe/Almacenes/listarTodosRequest", ReplyAction="http://services.softinv.pucp.edu.pe/Almacenes/listarTodosResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(SoftInvBusiness.clienteSOAP.IOException), Action="http://services.softinv.pucp.edu.pe/Almacenes/listarTodos/Fault/IOException", Name="IOException")]
        [System.ServiceModel.FaultContractAttribute(typeof(SoftInvBusiness.clienteSOAP.InterruptedException), Action="http://services.softinv.pucp.edu.pe/Almacenes/listarTodos/Fault/InterruptedExcept" +
            "ion", Name="InterruptedException")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        SoftInvBusiness.clienteSOAP.listarTodosResponse listarTodos(SoftInvBusiness.clienteSOAP.listarTodosRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.softinv.pucp.edu.pe/Almacenes/listarTodosRequest", ReplyAction="http://services.softinv.pucp.edu.pe/Almacenes/listarTodosResponse")]
        System.Threading.Tasks.Task<SoftInvBusiness.clienteSOAP.listarTodosResponse> listarTodosAsync(SoftInvBusiness.clienteSOAP.listarTodosRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="obtenerPorId", WrapperNamespace="http://services.softinv.pucp.edu.pe/", IsWrapped=true)]
    public partial class obtenerPorIdRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.softinv.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int id;
        
        public obtenerPorIdRequest() {
        }
        
        public obtenerPorIdRequest(int id) {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="obtenerPorIdResponse", WrapperNamespace="http://services.softinv.pucp.edu.pe/", IsWrapped=true)]
    public partial class obtenerPorIdResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.softinv.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SoftInvBusiness.clienteSOAP.almacenesDTO @return;
        
        public obtenerPorIdResponse() {
        }
        
        public obtenerPorIdResponse(SoftInvBusiness.clienteSOAP.almacenesDTO @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="inserta_almacen", WrapperNamespace="http://services.softinv.pucp.edu.pe/", IsWrapped=true)]
    public partial class inserta_almacenRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.softinv.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string nombre;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.softinv.pucp.edu.pe/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool almacen_central;
        
        public inserta_almacenRequest() {
        }
        
        public inserta_almacenRequest(string nombre, bool almacen_central) {
            this.nombre = nombre;
            this.almacen_central = almacen_central;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="inserta_almacenResponse", WrapperNamespace="http://services.softinv.pucp.edu.pe/", IsWrapped=true)]
    public partial class inserta_almacenResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.softinv.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public inserta_almacenResponse() {
        }
        
        public inserta_almacenResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="eliminar", WrapperNamespace="http://services.softinv.pucp.edu.pe/", IsWrapped=true)]
    public partial class eliminarRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.softinv.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int almacenId;
        
        public eliminarRequest() {
        }
        
        public eliminarRequest(int almacenId) {
            this.almacenId = almacenId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="eliminarResponse", WrapperNamespace="http://services.softinv.pucp.edu.pe/", IsWrapped=true)]
    public partial class eliminarResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.softinv.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public eliminarResponse() {
        }
        
        public eliminarResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="modificar", WrapperNamespace="http://services.softinv.pucp.edu.pe/", IsWrapped=true)]
    public partial class modificarRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.softinv.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int almacenId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.softinv.pucp.edu.pe/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string nombre;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.softinv.pucp.edu.pe/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool almacen_central;
        
        public modificarRequest() {
        }
        
        public modificarRequest(int almacenId, string nombre, bool almacen_central) {
            this.almacenId = almacenId;
            this.nombre = nombre;
            this.almacen_central = almacen_central;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="modificarResponse", WrapperNamespace="http://services.softinv.pucp.edu.pe/", IsWrapped=true)]
    public partial class modificarResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.softinv.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public modificarResponse() {
        }
        
        public modificarResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="reporteTipoProducto", WrapperNamespace="http://services.softinv.pucp.edu.pe/", IsWrapped=true)]
    public partial class reporteTipoProductoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.softinv.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int tipoProductoId;
        
        public reporteTipoProductoRequest() {
        }
        
        public reporteTipoProductoRequest(int tipoProductoId) {
            this.tipoProductoId = tipoProductoId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="reporteTipoProductoResponse", WrapperNamespace="http://services.softinv.pucp.edu.pe/", IsWrapped=true)]
    public partial class reporteTipoProductoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.softinv.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="base64Binary", IsNullable=true)]
        public byte[] @return;
        
        public reporteTipoProductoResponse() {
        }
        
        public reporteTipoProductoResponse(byte[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="reporteProducto", WrapperNamespace="http://services.softinv.pucp.edu.pe/", IsWrapped=true)]
    public partial class reporteProductoRequest {
        
        public reporteProductoRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="reporteProductoResponse", WrapperNamespace="http://services.softinv.pucp.edu.pe/", IsWrapped=true)]
    public partial class reporteProductoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.softinv.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="base64Binary", IsNullable=true)]
        public byte[] @return;
        
        public reporteProductoResponse() {
        }
        
        public reporteProductoResponse(byte[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarTodos", WrapperNamespace="http://services.softinv.pucp.edu.pe/", IsWrapped=true)]
    public partial class listarTodosRequest {
        
        public listarTodosRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarTodosResponse", WrapperNamespace="http://services.softinv.pucp.edu.pe/", IsWrapped=true)]
    public partial class listarTodosResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.softinv.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SoftInvBusiness.clienteSOAP.almacenesDTO[] @return;
        
        public listarTodosResponse() {
        }
        
        public listarTodosResponse(SoftInvBusiness.clienteSOAP.almacenesDTO[] @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface AlmacenesChannel : SoftInvBusiness.clienteSOAP.Almacenes, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AlmacenesClient : System.ServiceModel.ClientBase<SoftInvBusiness.clienteSOAP.Almacenes>, SoftInvBusiness.clienteSOAP.Almacenes {
        
        public AlmacenesClient() {
        }
        
        public AlmacenesClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AlmacenesClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AlmacenesClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AlmacenesClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SoftInvBusiness.clienteSOAP.obtenerPorIdResponse SoftInvBusiness.clienteSOAP.Almacenes.obtenerPorId(SoftInvBusiness.clienteSOAP.obtenerPorIdRequest request) {
            return base.Channel.obtenerPorId(request);
        }
        
        public SoftInvBusiness.clienteSOAP.almacenesDTO obtenerPorId(int id) {
            SoftInvBusiness.clienteSOAP.obtenerPorIdRequest inValue = new SoftInvBusiness.clienteSOAP.obtenerPorIdRequest();
            inValue.id = id;
            SoftInvBusiness.clienteSOAP.obtenerPorIdResponse retVal = ((SoftInvBusiness.clienteSOAP.Almacenes)(this)).obtenerPorId(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SoftInvBusiness.clienteSOAP.obtenerPorIdResponse> SoftInvBusiness.clienteSOAP.Almacenes.obtenerPorIdAsync(SoftInvBusiness.clienteSOAP.obtenerPorIdRequest request) {
            return base.Channel.obtenerPorIdAsync(request);
        }
        
        public System.Threading.Tasks.Task<SoftInvBusiness.clienteSOAP.obtenerPorIdResponse> obtenerPorIdAsync(int id) {
            SoftInvBusiness.clienteSOAP.obtenerPorIdRequest inValue = new SoftInvBusiness.clienteSOAP.obtenerPorIdRequest();
            inValue.id = id;
            return ((SoftInvBusiness.clienteSOAP.Almacenes)(this)).obtenerPorIdAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SoftInvBusiness.clienteSOAP.inserta_almacenResponse SoftInvBusiness.clienteSOAP.Almacenes.inserta_almacen(SoftInvBusiness.clienteSOAP.inserta_almacenRequest request) {
            return base.Channel.inserta_almacen(request);
        }
        
        public int inserta_almacen(string nombre, bool almacen_central) {
            SoftInvBusiness.clienteSOAP.inserta_almacenRequest inValue = new SoftInvBusiness.clienteSOAP.inserta_almacenRequest();
            inValue.nombre = nombre;
            inValue.almacen_central = almacen_central;
            SoftInvBusiness.clienteSOAP.inserta_almacenResponse retVal = ((SoftInvBusiness.clienteSOAP.Almacenes)(this)).inserta_almacen(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SoftInvBusiness.clienteSOAP.inserta_almacenResponse> SoftInvBusiness.clienteSOAP.Almacenes.inserta_almacenAsync(SoftInvBusiness.clienteSOAP.inserta_almacenRequest request) {
            return base.Channel.inserta_almacenAsync(request);
        }
        
        public System.Threading.Tasks.Task<SoftInvBusiness.clienteSOAP.inserta_almacenResponse> inserta_almacenAsync(string nombre, bool almacen_central) {
            SoftInvBusiness.clienteSOAP.inserta_almacenRequest inValue = new SoftInvBusiness.clienteSOAP.inserta_almacenRequest();
            inValue.nombre = nombre;
            inValue.almacen_central = almacen_central;
            return ((SoftInvBusiness.clienteSOAP.Almacenes)(this)).inserta_almacenAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SoftInvBusiness.clienteSOAP.eliminarResponse SoftInvBusiness.clienteSOAP.Almacenes.eliminar(SoftInvBusiness.clienteSOAP.eliminarRequest request) {
            return base.Channel.eliminar(request);
        }
        
        public int eliminar(int almacenId) {
            SoftInvBusiness.clienteSOAP.eliminarRequest inValue = new SoftInvBusiness.clienteSOAP.eliminarRequest();
            inValue.almacenId = almacenId;
            SoftInvBusiness.clienteSOAP.eliminarResponse retVal = ((SoftInvBusiness.clienteSOAP.Almacenes)(this)).eliminar(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SoftInvBusiness.clienteSOAP.eliminarResponse> SoftInvBusiness.clienteSOAP.Almacenes.eliminarAsync(SoftInvBusiness.clienteSOAP.eliminarRequest request) {
            return base.Channel.eliminarAsync(request);
        }
        
        public System.Threading.Tasks.Task<SoftInvBusiness.clienteSOAP.eliminarResponse> eliminarAsync(int almacenId) {
            SoftInvBusiness.clienteSOAP.eliminarRequest inValue = new SoftInvBusiness.clienteSOAP.eliminarRequest();
            inValue.almacenId = almacenId;
            return ((SoftInvBusiness.clienteSOAP.Almacenes)(this)).eliminarAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SoftInvBusiness.clienteSOAP.modificarResponse SoftInvBusiness.clienteSOAP.Almacenes.modificar(SoftInvBusiness.clienteSOAP.modificarRequest request) {
            return base.Channel.modificar(request);
        }
        
        public int modificar(int almacenId, string nombre, bool almacen_central) {
            SoftInvBusiness.clienteSOAP.modificarRequest inValue = new SoftInvBusiness.clienteSOAP.modificarRequest();
            inValue.almacenId = almacenId;
            inValue.nombre = nombre;
            inValue.almacen_central = almacen_central;
            SoftInvBusiness.clienteSOAP.modificarResponse retVal = ((SoftInvBusiness.clienteSOAP.Almacenes)(this)).modificar(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SoftInvBusiness.clienteSOAP.modificarResponse> SoftInvBusiness.clienteSOAP.Almacenes.modificarAsync(SoftInvBusiness.clienteSOAP.modificarRequest request) {
            return base.Channel.modificarAsync(request);
        }
        
        public System.Threading.Tasks.Task<SoftInvBusiness.clienteSOAP.modificarResponse> modificarAsync(int almacenId, string nombre, bool almacen_central) {
            SoftInvBusiness.clienteSOAP.modificarRequest inValue = new SoftInvBusiness.clienteSOAP.modificarRequest();
            inValue.almacenId = almacenId;
            inValue.nombre = nombre;
            inValue.almacen_central = almacen_central;
            return ((SoftInvBusiness.clienteSOAP.Almacenes)(this)).modificarAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SoftInvBusiness.clienteSOAP.reporteTipoProductoResponse SoftInvBusiness.clienteSOAP.Almacenes.reporteTipoProducto(SoftInvBusiness.clienteSOAP.reporteTipoProductoRequest request) {
            return base.Channel.reporteTipoProducto(request);
        }
        
        public byte[] reporteTipoProducto(int tipoProductoId) {
            SoftInvBusiness.clienteSOAP.reporteTipoProductoRequest inValue = new SoftInvBusiness.clienteSOAP.reporteTipoProductoRequest();
            inValue.tipoProductoId = tipoProductoId;
            SoftInvBusiness.clienteSOAP.reporteTipoProductoResponse retVal = ((SoftInvBusiness.clienteSOAP.Almacenes)(this)).reporteTipoProducto(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SoftInvBusiness.clienteSOAP.reporteTipoProductoResponse> SoftInvBusiness.clienteSOAP.Almacenes.reporteTipoProductoAsync(SoftInvBusiness.clienteSOAP.reporteTipoProductoRequest request) {
            return base.Channel.reporteTipoProductoAsync(request);
        }
        
        public System.Threading.Tasks.Task<SoftInvBusiness.clienteSOAP.reporteTipoProductoResponse> reporteTipoProductoAsync(int tipoProductoId) {
            SoftInvBusiness.clienteSOAP.reporteTipoProductoRequest inValue = new SoftInvBusiness.clienteSOAP.reporteTipoProductoRequest();
            inValue.tipoProductoId = tipoProductoId;
            return ((SoftInvBusiness.clienteSOAP.Almacenes)(this)).reporteTipoProductoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SoftInvBusiness.clienteSOAP.reporteProductoResponse SoftInvBusiness.clienteSOAP.Almacenes.reporteProducto(SoftInvBusiness.clienteSOAP.reporteProductoRequest request) {
            return base.Channel.reporteProducto(request);
        }
        
        public byte[] reporteProducto() {
            SoftInvBusiness.clienteSOAP.reporteProductoRequest inValue = new SoftInvBusiness.clienteSOAP.reporteProductoRequest();
            SoftInvBusiness.clienteSOAP.reporteProductoResponse retVal = ((SoftInvBusiness.clienteSOAP.Almacenes)(this)).reporteProducto(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SoftInvBusiness.clienteSOAP.reporteProductoResponse> SoftInvBusiness.clienteSOAP.Almacenes.reporteProductoAsync(SoftInvBusiness.clienteSOAP.reporteProductoRequest request) {
            return base.Channel.reporteProductoAsync(request);
        }
        
        public System.Threading.Tasks.Task<SoftInvBusiness.clienteSOAP.reporteProductoResponse> reporteProductoAsync() {
            SoftInvBusiness.clienteSOAP.reporteProductoRequest inValue = new SoftInvBusiness.clienteSOAP.reporteProductoRequest();
            return ((SoftInvBusiness.clienteSOAP.Almacenes)(this)).reporteProductoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SoftInvBusiness.clienteSOAP.listarTodosResponse SoftInvBusiness.clienteSOAP.Almacenes.listarTodos(SoftInvBusiness.clienteSOAP.listarTodosRequest request) {
            return base.Channel.listarTodos(request);
        }
        
        public SoftInvBusiness.clienteSOAP.almacenesDTO[] listarTodos() {
            SoftInvBusiness.clienteSOAP.listarTodosRequest inValue = new SoftInvBusiness.clienteSOAP.listarTodosRequest();
            SoftInvBusiness.clienteSOAP.listarTodosResponse retVal = ((SoftInvBusiness.clienteSOAP.Almacenes)(this)).listarTodos(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SoftInvBusiness.clienteSOAP.listarTodosResponse> SoftInvBusiness.clienteSOAP.Almacenes.listarTodosAsync(SoftInvBusiness.clienteSOAP.listarTodosRequest request) {
            return base.Channel.listarTodosAsync(request);
        }
        
        public System.Threading.Tasks.Task<SoftInvBusiness.clienteSOAP.listarTodosResponse> listarTodosAsync() {
            SoftInvBusiness.clienteSOAP.listarTodosRequest inValue = new SoftInvBusiness.clienteSOAP.listarTodosRequest();
            return ((SoftInvBusiness.clienteSOAP.Almacenes)(this)).listarTodosAsync(inValue);
        }
    }
}
