//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SoftVenBusiness.productoWS {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://services.softven.pucp.edu.pe/", ConfigurationName="productoWS.Productos")]
    public interface Productos {
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.softven.pucp.edu.pe/Productos/insertarRequest", ReplyAction="http://services.softven.pucp.edu.pe/Productos/insertarResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        SoftVenBusiness.productoWS.insertarResponse insertar(SoftVenBusiness.productoWS.insertarRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.softven.pucp.edu.pe/Productos/insertarRequest", ReplyAction="http://services.softven.pucp.edu.pe/Productos/insertarResponse")]
        System.Threading.Tasks.Task<SoftVenBusiness.productoWS.insertarResponse> insertarAsync(SoftVenBusiness.productoWS.insertarRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.softven.pucp.edu.pe/Productos/modificarRequest", ReplyAction="http://services.softven.pucp.edu.pe/Productos/modificarResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        SoftVenBusiness.productoWS.modificarResponse modificar(SoftVenBusiness.productoWS.modificarRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.softven.pucp.edu.pe/Productos/modificarRequest", ReplyAction="http://services.softven.pucp.edu.pe/Productos/modificarResponse")]
        System.Threading.Tasks.Task<SoftVenBusiness.productoWS.modificarResponse> modificarAsync(SoftVenBusiness.productoWS.modificarRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.softven.pucp.edu.pe/Productos/eliminarRequest", ReplyAction="http://services.softven.pucp.edu.pe/Productos/eliminarResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        SoftVenBusiness.productoWS.eliminarResponse eliminar(SoftVenBusiness.productoWS.eliminarRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.softven.pucp.edu.pe/Productos/eliminarRequest", ReplyAction="http://services.softven.pucp.edu.pe/Productos/eliminarResponse")]
        System.Threading.Tasks.Task<SoftVenBusiness.productoWS.eliminarResponse> eliminarAsync(SoftVenBusiness.productoWS.eliminarRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.softven.pucp.edu.pe/Productos/obtenerPorIdRequest", ReplyAction="http://services.softven.pucp.edu.pe/Productos/obtenerPorIdResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        SoftVenBusiness.productoWS.obtenerPorIdResponse obtenerPorId(SoftVenBusiness.productoWS.obtenerPorIdRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.softven.pucp.edu.pe/Productos/obtenerPorIdRequest", ReplyAction="http://services.softven.pucp.edu.pe/Productos/obtenerPorIdResponse")]
        System.Threading.Tasks.Task<SoftVenBusiness.productoWS.obtenerPorIdResponse> obtenerPorIdAsync(SoftVenBusiness.productoWS.obtenerPorIdRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.softven.pucp.edu.pe/Productos/listarTodosRequest", ReplyAction="http://services.softven.pucp.edu.pe/Productos/listarTodosResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        SoftVenBusiness.productoWS.listarTodosResponse listarTodos(SoftVenBusiness.productoWS.listarTodosRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.softven.pucp.edu.pe/Productos/listarTodosRequest", ReplyAction="http://services.softven.pucp.edu.pe/Productos/listarTodosResponse")]
        System.Threading.Tasks.Task<SoftVenBusiness.productoWS.listarTodosResponse> listarTodosAsync(SoftVenBusiness.productoWS.listarTodosRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="insertar", WrapperNamespace="http://services.softven.pucp.edu.pe/", IsWrapped=true)]
    public partial class insertarRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.softven.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string nombre;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.softven.pucp.edu.pe/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string descripcion;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.softven.pucp.edu.pe/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public double precio;
        
        public insertarRequest() {
        }
        
        public insertarRequest(string nombre, string descripcion, double precio) {
            this.nombre = nombre;
            this.descripcion = descripcion;
            this.precio = precio;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="insertarResponse", WrapperNamespace="http://services.softven.pucp.edu.pe/", IsWrapped=true)]
    public partial class insertarResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.softven.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public insertarResponse() {
        }
        
        public insertarResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="modificar", WrapperNamespace="http://services.softven.pucp.edu.pe/", IsWrapped=true)]
    public partial class modificarRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.softven.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int productoId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.softven.pucp.edu.pe/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string nombre;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.softven.pucp.edu.pe/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string descripcion;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.softven.pucp.edu.pe/", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public double precio;
        
        public modificarRequest() {
        }
        
        public modificarRequest(int productoId, string nombre, string descripcion, double precio) {
            this.productoId = productoId;
            this.nombre = nombre;
            this.descripcion = descripcion;
            this.precio = precio;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="modificarResponse", WrapperNamespace="http://services.softven.pucp.edu.pe/", IsWrapped=true)]
    public partial class modificarResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.softven.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public modificarResponse() {
        }
        
        public modificarResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="eliminar", WrapperNamespace="http://services.softven.pucp.edu.pe/", IsWrapped=true)]
    public partial class eliminarRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.softven.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int productoId;
        
        public eliminarRequest() {
        }
        
        public eliminarRequest(int productoId) {
            this.productoId = productoId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="eliminarResponse", WrapperNamespace="http://services.softven.pucp.edu.pe/", IsWrapped=true)]
    public partial class eliminarResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.softven.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public eliminarResponse() {
        }
        
        public eliminarResponse(int @return) {
            this.@return = @return;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.softven.pucp.edu.pe/")]
    public partial class productosDTO : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string descripcionField;
        
        private string nombreField;
        
        private double precioField;
        
        private bool precioFieldSpecified;
        
        private int productoIdField;
        
        private bool productoIdFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string descripcion {
            get {
                return this.descripcionField;
            }
            set {
                this.descripcionField = value;
                this.RaisePropertyChanged("descripcion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
                this.RaisePropertyChanged("nombre");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public double precio {
            get {
                return this.precioField;
            }
            set {
                this.precioField = value;
                this.RaisePropertyChanged("precio");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool precioSpecified {
            get {
                return this.precioFieldSpecified;
            }
            set {
                this.precioFieldSpecified = value;
                this.RaisePropertyChanged("precioSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public int productoId {
            get {
                return this.productoIdField;
            }
            set {
                this.productoIdField = value;
                this.RaisePropertyChanged("productoId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool productoIdSpecified {
            get {
                return this.productoIdFieldSpecified;
            }
            set {
                this.productoIdFieldSpecified = value;
                this.RaisePropertyChanged("productoIdSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="obtenerPorId", WrapperNamespace="http://services.softven.pucp.edu.pe/", IsWrapped=true)]
    public partial class obtenerPorIdRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.softven.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int productoId;
        
        public obtenerPorIdRequest() {
        }
        
        public obtenerPorIdRequest(int productoId) {
            this.productoId = productoId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="obtenerPorIdResponse", WrapperNamespace="http://services.softven.pucp.edu.pe/", IsWrapped=true)]
    public partial class obtenerPorIdResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.softven.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SoftVenBusiness.productoWS.productosDTO @return;
        
        public obtenerPorIdResponse() {
        }
        
        public obtenerPorIdResponse(SoftVenBusiness.productoWS.productosDTO @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarTodos", WrapperNamespace="http://services.softven.pucp.edu.pe/", IsWrapped=true)]
    public partial class listarTodosRequest {
        
        public listarTodosRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarTodosResponse", WrapperNamespace="http://services.softven.pucp.edu.pe/", IsWrapped=true)]
    public partial class listarTodosResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.softven.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SoftVenBusiness.productoWS.productosDTO[] @return;
        
        public listarTodosResponse() {
        }
        
        public listarTodosResponse(SoftVenBusiness.productoWS.productosDTO[] @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ProductosChannel : SoftVenBusiness.productoWS.Productos, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ProductosClient : System.ServiceModel.ClientBase<SoftVenBusiness.productoWS.Productos>, SoftVenBusiness.productoWS.Productos {
        
        public ProductosClient() {
        }
        
        public ProductosClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ProductosClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ProductosClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ProductosClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SoftVenBusiness.productoWS.insertarResponse SoftVenBusiness.productoWS.Productos.insertar(SoftVenBusiness.productoWS.insertarRequest request) {
            return base.Channel.insertar(request);
        }
        
        public int insertar(string nombre, string descripcion, double precio) {
            SoftVenBusiness.productoWS.insertarRequest inValue = new SoftVenBusiness.productoWS.insertarRequest();
            inValue.nombre = nombre;
            inValue.descripcion = descripcion;
            inValue.precio = precio;
            SoftVenBusiness.productoWS.insertarResponse retVal = ((SoftVenBusiness.productoWS.Productos)(this)).insertar(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SoftVenBusiness.productoWS.insertarResponse> SoftVenBusiness.productoWS.Productos.insertarAsync(SoftVenBusiness.productoWS.insertarRequest request) {
            return base.Channel.insertarAsync(request);
        }
        
        public System.Threading.Tasks.Task<SoftVenBusiness.productoWS.insertarResponse> insertarAsync(string nombre, string descripcion, double precio) {
            SoftVenBusiness.productoWS.insertarRequest inValue = new SoftVenBusiness.productoWS.insertarRequest();
            inValue.nombre = nombre;
            inValue.descripcion = descripcion;
            inValue.precio = precio;
            return ((SoftVenBusiness.productoWS.Productos)(this)).insertarAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SoftVenBusiness.productoWS.modificarResponse SoftVenBusiness.productoWS.Productos.modificar(SoftVenBusiness.productoWS.modificarRequest request) {
            return base.Channel.modificar(request);
        }
        
        public int modificar(int productoId, string nombre, string descripcion, double precio) {
            SoftVenBusiness.productoWS.modificarRequest inValue = new SoftVenBusiness.productoWS.modificarRequest();
            inValue.productoId = productoId;
            inValue.nombre = nombre;
            inValue.descripcion = descripcion;
            inValue.precio = precio;
            SoftVenBusiness.productoWS.modificarResponse retVal = ((SoftVenBusiness.productoWS.Productos)(this)).modificar(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SoftVenBusiness.productoWS.modificarResponse> SoftVenBusiness.productoWS.Productos.modificarAsync(SoftVenBusiness.productoWS.modificarRequest request) {
            return base.Channel.modificarAsync(request);
        }
        
        public System.Threading.Tasks.Task<SoftVenBusiness.productoWS.modificarResponse> modificarAsync(int productoId, string nombre, string descripcion, double precio) {
            SoftVenBusiness.productoWS.modificarRequest inValue = new SoftVenBusiness.productoWS.modificarRequest();
            inValue.productoId = productoId;
            inValue.nombre = nombre;
            inValue.descripcion = descripcion;
            inValue.precio = precio;
            return ((SoftVenBusiness.productoWS.Productos)(this)).modificarAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SoftVenBusiness.productoWS.eliminarResponse SoftVenBusiness.productoWS.Productos.eliminar(SoftVenBusiness.productoWS.eliminarRequest request) {
            return base.Channel.eliminar(request);
        }
        
        public int eliminar(int productoId) {
            SoftVenBusiness.productoWS.eliminarRequest inValue = new SoftVenBusiness.productoWS.eliminarRequest();
            inValue.productoId = productoId;
            SoftVenBusiness.productoWS.eliminarResponse retVal = ((SoftVenBusiness.productoWS.Productos)(this)).eliminar(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SoftVenBusiness.productoWS.eliminarResponse> SoftVenBusiness.productoWS.Productos.eliminarAsync(SoftVenBusiness.productoWS.eliminarRequest request) {
            return base.Channel.eliminarAsync(request);
        }
        
        public System.Threading.Tasks.Task<SoftVenBusiness.productoWS.eliminarResponse> eliminarAsync(int productoId) {
            SoftVenBusiness.productoWS.eliminarRequest inValue = new SoftVenBusiness.productoWS.eliminarRequest();
            inValue.productoId = productoId;
            return ((SoftVenBusiness.productoWS.Productos)(this)).eliminarAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SoftVenBusiness.productoWS.obtenerPorIdResponse SoftVenBusiness.productoWS.Productos.obtenerPorId(SoftVenBusiness.productoWS.obtenerPorIdRequest request) {
            return base.Channel.obtenerPorId(request);
        }
        
        public SoftVenBusiness.productoWS.productosDTO obtenerPorId(int productoId) {
            SoftVenBusiness.productoWS.obtenerPorIdRequest inValue = new SoftVenBusiness.productoWS.obtenerPorIdRequest();
            inValue.productoId = productoId;
            SoftVenBusiness.productoWS.obtenerPorIdResponse retVal = ((SoftVenBusiness.productoWS.Productos)(this)).obtenerPorId(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SoftVenBusiness.productoWS.obtenerPorIdResponse> SoftVenBusiness.productoWS.Productos.obtenerPorIdAsync(SoftVenBusiness.productoWS.obtenerPorIdRequest request) {
            return base.Channel.obtenerPorIdAsync(request);
        }
        
        public System.Threading.Tasks.Task<SoftVenBusiness.productoWS.obtenerPorIdResponse> obtenerPorIdAsync(int productoId) {
            SoftVenBusiness.productoWS.obtenerPorIdRequest inValue = new SoftVenBusiness.productoWS.obtenerPorIdRequest();
            inValue.productoId = productoId;
            return ((SoftVenBusiness.productoWS.Productos)(this)).obtenerPorIdAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SoftVenBusiness.productoWS.listarTodosResponse SoftVenBusiness.productoWS.Productos.listarTodos(SoftVenBusiness.productoWS.listarTodosRequest request) {
            return base.Channel.listarTodos(request);
        }
        
        public SoftVenBusiness.productoWS.productosDTO[] listarTodos() {
            SoftVenBusiness.productoWS.listarTodosRequest inValue = new SoftVenBusiness.productoWS.listarTodosRequest();
            SoftVenBusiness.productoWS.listarTodosResponse retVal = ((SoftVenBusiness.productoWS.Productos)(this)).listarTodos(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SoftVenBusiness.productoWS.listarTodosResponse> SoftVenBusiness.productoWS.Productos.listarTodosAsync(SoftVenBusiness.productoWS.listarTodosRequest request) {
            return base.Channel.listarTodosAsync(request);
        }
        
        public System.Threading.Tasks.Task<SoftVenBusiness.productoWS.listarTodosResponse> listarTodosAsync() {
            SoftVenBusiness.productoWS.listarTodosRequest inValue = new SoftVenBusiness.productoWS.listarTodosRequest();
            return ((SoftVenBusiness.productoWS.Productos)(this)).listarTodosAsync(inValue);
        }
    }
}
