//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClienteRENIEC.RENIEC {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://services.softRENIEC.pucp.edu.pe/", ConfigurationName="RENIEC.ConsultaDNI")]
    public interface ConsultaDNI {
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.softRENIEC.pucp.edu.pe/ConsultaDNI/consultaRequest", ReplyAction="http://services.softRENIEC.pucp.edu.pe/ConsultaDNI/consultaResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        ClienteRENIEC.RENIEC.consultaResponse consulta(ClienteRENIEC.RENIEC.consultaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.softRENIEC.pucp.edu.pe/ConsultaDNI/consultaRequest", ReplyAction="http://services.softRENIEC.pucp.edu.pe/ConsultaDNI/consultaResponse")]
        System.Threading.Tasks.Task<ClienteRENIEC.RENIEC.consultaResponse> consultaAsync(ClienteRENIEC.RENIEC.consultaRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.softRENIEC.pucp.edu.pe/")]
    public partial class personasDTO : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string dNIField;
        
        private string maternoField;
        
        private string nombresField;
        
        private string paternoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string DNI {
            get {
                return this.dNIField;
            }
            set {
                this.dNIField = value;
                this.RaisePropertyChanged("DNI");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string materno {
            get {
                return this.maternoField;
            }
            set {
                this.maternoField = value;
                this.RaisePropertyChanged("materno");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string nombres {
            get {
                return this.nombresField;
            }
            set {
                this.nombresField = value;
                this.RaisePropertyChanged("nombres");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string paterno {
            get {
                return this.paternoField;
            }
            set {
                this.paternoField = value;
                this.RaisePropertyChanged("paterno");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="consulta", WrapperNamespace="http://services.softRENIEC.pucp.edu.pe/", IsWrapped=true)]
    public partial class consultaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.softRENIEC.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string DNI;
        
        public consultaRequest() {
        }
        
        public consultaRequest(string DNI) {
            this.DNI = DNI;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="consultaResponse", WrapperNamespace="http://services.softRENIEC.pucp.edu.pe/", IsWrapped=true)]
    public partial class consultaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.softRENIEC.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ClienteRENIEC.RENIEC.personasDTO @return;
        
        public consultaResponse() {
        }
        
        public consultaResponse(ClienteRENIEC.RENIEC.personasDTO @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ConsultaDNIChannel : ClienteRENIEC.RENIEC.ConsultaDNI, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ConsultaDNIClient : System.ServiceModel.ClientBase<ClienteRENIEC.RENIEC.ConsultaDNI>, ClienteRENIEC.RENIEC.ConsultaDNI {
        
        public ConsultaDNIClient() {
        }
        
        public ConsultaDNIClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ConsultaDNIClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ConsultaDNIClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ConsultaDNIClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ClienteRENIEC.RENIEC.consultaResponse ClienteRENIEC.RENIEC.ConsultaDNI.consulta(ClienteRENIEC.RENIEC.consultaRequest request) {
            return base.Channel.consulta(request);
        }
        
        public ClienteRENIEC.RENIEC.personasDTO consulta(string DNI) {
            ClienteRENIEC.RENIEC.consultaRequest inValue = new ClienteRENIEC.RENIEC.consultaRequest();
            inValue.DNI = DNI;
            ClienteRENIEC.RENIEC.consultaResponse retVal = ((ClienteRENIEC.RENIEC.ConsultaDNI)(this)).consulta(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ClienteRENIEC.RENIEC.consultaResponse> ClienteRENIEC.RENIEC.ConsultaDNI.consultaAsync(ClienteRENIEC.RENIEC.consultaRequest request) {
            return base.Channel.consultaAsync(request);
        }
        
        public System.Threading.Tasks.Task<ClienteRENIEC.RENIEC.consultaResponse> consultaAsync(string DNI) {
            ClienteRENIEC.RENIEC.consultaRequest inValue = new ClienteRENIEC.RENIEC.consultaRequest();
            inValue.DNI = DNI;
            return ((ClienteRENIEC.RENIEC.ConsultaDNI)(this)).consultaAsync(inValue);
        }
    }
}
