//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SoftInvBusiness.SoftInvWSAlmacenes {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://softinvws.services.softinv.pucp.edu.pe/", ConfigurationName="SoftInvWSAlmacenes.Almacenes")]
    public interface Almacenes {
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://softinvws.services.softinv.pucp.edu.pe/Almacenes/eliminarRequest", ReplyAction="http://softinvws.services.softinv.pucp.edu.pe/Almacenes/eliminarResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        SoftInvBusiness.SoftInvWSAlmacenes.eliminarResponse eliminar(SoftInvBusiness.SoftInvWSAlmacenes.eliminarRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://softinvws.services.softinv.pucp.edu.pe/Almacenes/eliminarRequest", ReplyAction="http://softinvws.services.softinv.pucp.edu.pe/Almacenes/eliminarResponse")]
        System.Threading.Tasks.Task<SoftInvBusiness.SoftInvWSAlmacenes.eliminarResponse> eliminarAsync(SoftInvBusiness.SoftInvWSAlmacenes.eliminarRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://softinvws.services.softinv.pucp.edu.pe/Almacenes/modificarRequest", ReplyAction="http://softinvws.services.softinv.pucp.edu.pe/Almacenes/modificarResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        SoftInvBusiness.SoftInvWSAlmacenes.modificarResponse modificar(SoftInvBusiness.SoftInvWSAlmacenes.modificarRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://softinvws.services.softinv.pucp.edu.pe/Almacenes/modificarRequest", ReplyAction="http://softinvws.services.softinv.pucp.edu.pe/Almacenes/modificarResponse")]
        System.Threading.Tasks.Task<SoftInvBusiness.SoftInvWSAlmacenes.modificarResponse> modificarAsync(SoftInvBusiness.SoftInvWSAlmacenes.modificarRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://softinvws.services.softinv.pucp.edu.pe/Almacenes/insertar_almacenRequest", ReplyAction="http://softinvws.services.softinv.pucp.edu.pe/Almacenes/insertar_almacenResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        SoftInvBusiness.SoftInvWSAlmacenes.insertar_almacenResponse insertar_almacen(SoftInvBusiness.SoftInvWSAlmacenes.insertar_almacenRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://softinvws.services.softinv.pucp.edu.pe/Almacenes/insertar_almacenRequest", ReplyAction="http://softinvws.services.softinv.pucp.edu.pe/Almacenes/insertar_almacenResponse")]
        System.Threading.Tasks.Task<SoftInvBusiness.SoftInvWSAlmacenes.insertar_almacenResponse> insertar_almacenAsync(SoftInvBusiness.SoftInvWSAlmacenes.insertar_almacenRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://softinvws.services.softinv.pucp.edu.pe/Almacenes/obtenerPorIdRequest", ReplyAction="http://softinvws.services.softinv.pucp.edu.pe/Almacenes/obtenerPorIdResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        SoftInvBusiness.SoftInvWSAlmacenes.obtenerPorIdResponse obtenerPorId(SoftInvBusiness.SoftInvWSAlmacenes.obtenerPorIdRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://softinvws.services.softinv.pucp.edu.pe/Almacenes/obtenerPorIdRequest", ReplyAction="http://softinvws.services.softinv.pucp.edu.pe/Almacenes/obtenerPorIdResponse")]
        System.Threading.Tasks.Task<SoftInvBusiness.SoftInvWSAlmacenes.obtenerPorIdResponse> obtenerPorIdAsync(SoftInvBusiness.SoftInvWSAlmacenes.obtenerPorIdRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://softinvws.services.softinv.pucp.edu.pe/Almacenes/listarTodosRequest", ReplyAction="http://softinvws.services.softinv.pucp.edu.pe/Almacenes/listarTodosResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        SoftInvBusiness.SoftInvWSAlmacenes.listarTodosResponse listarTodos(SoftInvBusiness.SoftInvWSAlmacenes.listarTodosRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://softinvws.services.softinv.pucp.edu.pe/Almacenes/listarTodosRequest", ReplyAction="http://softinvws.services.softinv.pucp.edu.pe/Almacenes/listarTodosResponse")]
        System.Threading.Tasks.Task<SoftInvBusiness.SoftInvWSAlmacenes.listarTodosResponse> listarTodosAsync(SoftInvBusiness.SoftInvWSAlmacenes.listarTodosRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="eliminar", WrapperNamespace="http://softinvws.services.softinv.pucp.edu.pe/", IsWrapped=true)]
    public partial class eliminarRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://softinvws.services.softinv.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int arg0;
        
        public eliminarRequest() {
        }
        
        public eliminarRequest(int arg0) {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="eliminarResponse", WrapperNamespace="http://softinvws.services.softinv.pucp.edu.pe/", IsWrapped=true)]
    public partial class eliminarResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://softinvws.services.softinv.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public eliminarResponse() {
        }
        
        public eliminarResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="modificar", WrapperNamespace="http://softinvws.services.softinv.pucp.edu.pe/", IsWrapped=true)]
    public partial class modificarRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://softinvws.services.softinv.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int almacenId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://softinvws.services.softinv.pucp.edu.pe/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string nombre;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://softinvws.services.softinv.pucp.edu.pe/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool almacen_central;
        
        public modificarRequest() {
        }
        
        public modificarRequest(int almacenId, string nombre, bool almacen_central) {
            this.almacenId = almacenId;
            this.nombre = nombre;
            this.almacen_central = almacen_central;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="modificarResponse", WrapperNamespace="http://softinvws.services.softinv.pucp.edu.pe/", IsWrapped=true)]
    public partial class modificarResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://softinvws.services.softinv.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public modificarResponse() {
        }
        
        public modificarResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="insertar_almacen", WrapperNamespace="http://softinvws.services.softinv.pucp.edu.pe/", IsWrapped=true)]
    public partial class insertar_almacenRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://softinvws.services.softinv.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string nombre;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://softinvws.services.softinv.pucp.edu.pe/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool almacen_central;
        
        public insertar_almacenRequest() {
        }
        
        public insertar_almacenRequest(string nombre, bool almacen_central) {
            this.nombre = nombre;
            this.almacen_central = almacen_central;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="insertar_almacenResponse", WrapperNamespace="http://softinvws.services.softinv.pucp.edu.pe/", IsWrapped=true)]
    public partial class insertar_almacenResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://softinvws.services.softinv.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public insertar_almacenResponse() {
        }
        
        public insertar_almacenResponse(int @return) {
            this.@return = @return;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://softinvws.services.softinv.pucp.edu.pe/")]
    public partial class almacenesDTO : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int almacenIdField;
        
        private bool almacenIdFieldSpecified;
        
        private bool almacen_centralField;
        
        private bool almacen_centralFieldSpecified;
        
        private string nombreField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int almacenId {
            get {
                return this.almacenIdField;
            }
            set {
                this.almacenIdField = value;
                this.RaisePropertyChanged("almacenId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool almacenIdSpecified {
            get {
                return this.almacenIdFieldSpecified;
            }
            set {
                this.almacenIdFieldSpecified = value;
                this.RaisePropertyChanged("almacenIdSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public bool almacen_central {
            get {
                return this.almacen_centralField;
            }
            set {
                this.almacen_centralField = value;
                this.RaisePropertyChanged("almacen_central");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool almacen_centralSpecified {
            get {
                return this.almacen_centralFieldSpecified;
            }
            set {
                this.almacen_centralFieldSpecified = value;
                this.RaisePropertyChanged("almacen_centralSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
                this.RaisePropertyChanged("nombre");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="obtenerPorId", WrapperNamespace="http://softinvws.services.softinv.pucp.edu.pe/", IsWrapped=true)]
    public partial class obtenerPorIdRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://softinvws.services.softinv.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int id;
        
        public obtenerPorIdRequest() {
        }
        
        public obtenerPorIdRequest(int id) {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="obtenerPorIdResponse", WrapperNamespace="http://softinvws.services.softinv.pucp.edu.pe/", IsWrapped=true)]
    public partial class obtenerPorIdResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://softinvws.services.softinv.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SoftInvBusiness.SoftInvWSAlmacenes.almacenesDTO @return;
        
        public obtenerPorIdResponse() {
        }
        
        public obtenerPorIdResponse(SoftInvBusiness.SoftInvWSAlmacenes.almacenesDTO @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarTodos", WrapperNamespace="http://softinvws.services.softinv.pucp.edu.pe/", IsWrapped=true)]
    public partial class listarTodosRequest {
        
        public listarTodosRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarTodosResponse", WrapperNamespace="http://softinvws.services.softinv.pucp.edu.pe/", IsWrapped=true)]
    public partial class listarTodosResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://softinvws.services.softinv.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SoftInvBusiness.SoftInvWSAlmacenes.almacenesDTO[] @return;
        
        public listarTodosResponse() {
        }
        
        public listarTodosResponse(SoftInvBusiness.SoftInvWSAlmacenes.almacenesDTO[] @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface AlmacenesChannel : SoftInvBusiness.SoftInvWSAlmacenes.Almacenes, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AlmacenesClient : System.ServiceModel.ClientBase<SoftInvBusiness.SoftInvWSAlmacenes.Almacenes>, SoftInvBusiness.SoftInvWSAlmacenes.Almacenes {
        
        public AlmacenesClient() {
        }
        
        public AlmacenesClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AlmacenesClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AlmacenesClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AlmacenesClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SoftInvBusiness.SoftInvWSAlmacenes.eliminarResponse SoftInvBusiness.SoftInvWSAlmacenes.Almacenes.eliminar(SoftInvBusiness.SoftInvWSAlmacenes.eliminarRequest request) {
            return base.Channel.eliminar(request);
        }
        
        public int eliminar(int arg0) {
            SoftInvBusiness.SoftInvWSAlmacenes.eliminarRequest inValue = new SoftInvBusiness.SoftInvWSAlmacenes.eliminarRequest();
            inValue.arg0 = arg0;
            SoftInvBusiness.SoftInvWSAlmacenes.eliminarResponse retVal = ((SoftInvBusiness.SoftInvWSAlmacenes.Almacenes)(this)).eliminar(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SoftInvBusiness.SoftInvWSAlmacenes.eliminarResponse> SoftInvBusiness.SoftInvWSAlmacenes.Almacenes.eliminarAsync(SoftInvBusiness.SoftInvWSAlmacenes.eliminarRequest request) {
            return base.Channel.eliminarAsync(request);
        }
        
        public System.Threading.Tasks.Task<SoftInvBusiness.SoftInvWSAlmacenes.eliminarResponse> eliminarAsync(int arg0) {
            SoftInvBusiness.SoftInvWSAlmacenes.eliminarRequest inValue = new SoftInvBusiness.SoftInvWSAlmacenes.eliminarRequest();
            inValue.arg0 = arg0;
            return ((SoftInvBusiness.SoftInvWSAlmacenes.Almacenes)(this)).eliminarAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SoftInvBusiness.SoftInvWSAlmacenes.modificarResponse SoftInvBusiness.SoftInvWSAlmacenes.Almacenes.modificar(SoftInvBusiness.SoftInvWSAlmacenes.modificarRequest request) {
            return base.Channel.modificar(request);
        }
        
        public int modificar(int almacenId, string nombre, bool almacen_central) {
            SoftInvBusiness.SoftInvWSAlmacenes.modificarRequest inValue = new SoftInvBusiness.SoftInvWSAlmacenes.modificarRequest();
            inValue.almacenId = almacenId;
            inValue.nombre = nombre;
            inValue.almacen_central = almacen_central;
            SoftInvBusiness.SoftInvWSAlmacenes.modificarResponse retVal = ((SoftInvBusiness.SoftInvWSAlmacenes.Almacenes)(this)).modificar(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SoftInvBusiness.SoftInvWSAlmacenes.modificarResponse> SoftInvBusiness.SoftInvWSAlmacenes.Almacenes.modificarAsync(SoftInvBusiness.SoftInvWSAlmacenes.modificarRequest request) {
            return base.Channel.modificarAsync(request);
        }
        
        public System.Threading.Tasks.Task<SoftInvBusiness.SoftInvWSAlmacenes.modificarResponse> modificarAsync(int almacenId, string nombre, bool almacen_central) {
            SoftInvBusiness.SoftInvWSAlmacenes.modificarRequest inValue = new SoftInvBusiness.SoftInvWSAlmacenes.modificarRequest();
            inValue.almacenId = almacenId;
            inValue.nombre = nombre;
            inValue.almacen_central = almacen_central;
            return ((SoftInvBusiness.SoftInvWSAlmacenes.Almacenes)(this)).modificarAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SoftInvBusiness.SoftInvWSAlmacenes.insertar_almacenResponse SoftInvBusiness.SoftInvWSAlmacenes.Almacenes.insertar_almacen(SoftInvBusiness.SoftInvWSAlmacenes.insertar_almacenRequest request) {
            return base.Channel.insertar_almacen(request);
        }
        
        public int insertar_almacen(string nombre, bool almacen_central) {
            SoftInvBusiness.SoftInvWSAlmacenes.insertar_almacenRequest inValue = new SoftInvBusiness.SoftInvWSAlmacenes.insertar_almacenRequest();
            inValue.nombre = nombre;
            inValue.almacen_central = almacen_central;
            SoftInvBusiness.SoftInvWSAlmacenes.insertar_almacenResponse retVal = ((SoftInvBusiness.SoftInvWSAlmacenes.Almacenes)(this)).insertar_almacen(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SoftInvBusiness.SoftInvWSAlmacenes.insertar_almacenResponse> SoftInvBusiness.SoftInvWSAlmacenes.Almacenes.insertar_almacenAsync(SoftInvBusiness.SoftInvWSAlmacenes.insertar_almacenRequest request) {
            return base.Channel.insertar_almacenAsync(request);
        }
        
        public System.Threading.Tasks.Task<SoftInvBusiness.SoftInvWSAlmacenes.insertar_almacenResponse> insertar_almacenAsync(string nombre, bool almacen_central) {
            SoftInvBusiness.SoftInvWSAlmacenes.insertar_almacenRequest inValue = new SoftInvBusiness.SoftInvWSAlmacenes.insertar_almacenRequest();
            inValue.nombre = nombre;
            inValue.almacen_central = almacen_central;
            return ((SoftInvBusiness.SoftInvWSAlmacenes.Almacenes)(this)).insertar_almacenAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SoftInvBusiness.SoftInvWSAlmacenes.obtenerPorIdResponse SoftInvBusiness.SoftInvWSAlmacenes.Almacenes.obtenerPorId(SoftInvBusiness.SoftInvWSAlmacenes.obtenerPorIdRequest request) {
            return base.Channel.obtenerPorId(request);
        }
        
        public SoftInvBusiness.SoftInvWSAlmacenes.almacenesDTO obtenerPorId(int id) {
            SoftInvBusiness.SoftInvWSAlmacenes.obtenerPorIdRequest inValue = new SoftInvBusiness.SoftInvWSAlmacenes.obtenerPorIdRequest();
            inValue.id = id;
            SoftInvBusiness.SoftInvWSAlmacenes.obtenerPorIdResponse retVal = ((SoftInvBusiness.SoftInvWSAlmacenes.Almacenes)(this)).obtenerPorId(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SoftInvBusiness.SoftInvWSAlmacenes.obtenerPorIdResponse> SoftInvBusiness.SoftInvWSAlmacenes.Almacenes.obtenerPorIdAsync(SoftInvBusiness.SoftInvWSAlmacenes.obtenerPorIdRequest request) {
            return base.Channel.obtenerPorIdAsync(request);
        }
        
        public System.Threading.Tasks.Task<SoftInvBusiness.SoftInvWSAlmacenes.obtenerPorIdResponse> obtenerPorIdAsync(int id) {
            SoftInvBusiness.SoftInvWSAlmacenes.obtenerPorIdRequest inValue = new SoftInvBusiness.SoftInvWSAlmacenes.obtenerPorIdRequest();
            inValue.id = id;
            return ((SoftInvBusiness.SoftInvWSAlmacenes.Almacenes)(this)).obtenerPorIdAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SoftInvBusiness.SoftInvWSAlmacenes.listarTodosResponse SoftInvBusiness.SoftInvWSAlmacenes.Almacenes.listarTodos(SoftInvBusiness.SoftInvWSAlmacenes.listarTodosRequest request) {
            return base.Channel.listarTodos(request);
        }
        
        public SoftInvBusiness.SoftInvWSAlmacenes.almacenesDTO[] listarTodos() {
            SoftInvBusiness.SoftInvWSAlmacenes.listarTodosRequest inValue = new SoftInvBusiness.SoftInvWSAlmacenes.listarTodosRequest();
            SoftInvBusiness.SoftInvWSAlmacenes.listarTodosResponse retVal = ((SoftInvBusiness.SoftInvWSAlmacenes.Almacenes)(this)).listarTodos(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SoftInvBusiness.SoftInvWSAlmacenes.listarTodosResponse> SoftInvBusiness.SoftInvWSAlmacenes.Almacenes.listarTodosAsync(SoftInvBusiness.SoftInvWSAlmacenes.listarTodosRequest request) {
            return base.Channel.listarTodosAsync(request);
        }
        
        public System.Threading.Tasks.Task<SoftInvBusiness.SoftInvWSAlmacenes.listarTodosResponse> listarTodosAsync() {
            SoftInvBusiness.SoftInvWSAlmacenes.listarTodosRequest inValue = new SoftInvBusiness.SoftInvWSAlmacenes.listarTodosRequest();
            return ((SoftInvBusiness.SoftInvWSAlmacenes.Almacenes)(this)).listarTodosAsync(inValue);
        }
    }
}
